server_ip: '127.0.0.1'    # minecraft 地址
server_port: 25565        # minecraft 端口
rcon_port: 25575          # minecraft rcon 端口
rcon_password: '8888'     # minecraft rcon 密码
db_host: "localhost"      # mysql地址
db_port: 3360             # mysql端口
db_user: "tcc"              # mysql用户名
db_passwd: "rver2024@"   # mysql密码
db_database: "tcc"        # 所用数据库
auth_group_list:          # bot工作qq群, 这些群里的人必须都是服务器玩家
  - '29647292'
  - '31819041'
  - '93646117'
  - '53603855'
auth_qq_list:             # 授权的qq号 (例如 /whitelist update 权限)
  - '3478'
  - '1120'
  - '3671'
code_prefix: '我是爱坤我{0,1}不[是做]小黑子'     # 白名单验证码前缀, 与服务器要一致
self_qq: 39752           # bot自己的qq号